image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - unit-test
  - integration-test

maven-build:
  image: maven:3-jdk-13
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

java:
  stage: unit-test
  script:
  - mvn verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml