version: '3'

services:
  client:
    image: soltanloo/jalas-frontend
    ports:
      - "3000:80"
    depends_on:
      - server
  server:
    image: soltanloo/jalas-backend
    restart: always
    ports:
      - "8000:8080"